# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "pp's world tree Mk.III"
description: > # this means to ignore newlines until "email:"
   Discovering, Thinking and Sharing

email: pp2moonbird#gmail.com
#blog logo
logo: "/assets/images/avatar.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "http://7sbymk.com1.z0.glb.clouddn.com/background_image.jpg"

name: 'pp'
author: 'pp'
author_image: "/assets/images/avatar.jpg"

paginate:	5

url: "http://www.pprollingstar.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@pp2moonbird'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/pp2moonbird
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/pp2moonbird
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
